// This is automatically generated by the Tiger compiler.
// Do NOT modify!

//------------------------structures------------------------
struct BinaryTree
{
  struct BinaryTree_vtable *vptr;
};

struct BT
{
  struct BT_vtable *vptr;
};

struct Tree
{
  struct Tree_vtable *vptr;
  struct Tree * left;
  struct Tree * right;
  int  key;
  int  has_left;
  int  has_right;
  struct Tree * my_null;
};

//-----------------------vtables structures-------------------------
struct BinaryTree_vtable
{
};

struct BT_vtable
{
  int  (*Start)();
};

struct Tree_vtable
{
  int  (*Init)();
  int  (*SetRight)();
  int  (*SetLeft)();
  struct Tree * (*GetRight)();
  struct Tree * (*GetLeft)();
  int  (*GetKey)();
  int  (*SetKey)();
  int  (*GetHas_Right)();
  int  (*GetHas_Left)();
  int  (*SetHas_Left)();
  int  (*SetHas_Right)();
  int  (*Compare)();
  int  (*Insert)();
  int  (*Delete)();
  int  (*Remove)();
  int  (*RemoveRight)();
  int  (*RemoveLeft)();
  int  (*Search)();
  int  (*Print)();
  int  (*RecPrint)();
};


//---------------------memory GC maps----------------------
char *Start_arguments_gc_map = "1";
char *Start_locals_gc_map = "100";

char *Init_arguments_gc_map = "10";
char *Init_locals_gc_map = "";

char *SetRight_arguments_gc_map = "11";
char *SetRight_locals_gc_map = "";

char *SetLeft_arguments_gc_map = "11";
char *SetLeft_locals_gc_map = "";

char *GetRight_arguments_gc_map = "1";
char *GetRight_locals_gc_map = "";

char *GetLeft_arguments_gc_map = "1";
char *GetLeft_locals_gc_map = "";

char *GetKey_arguments_gc_map = "1";
char *GetKey_locals_gc_map = "";

char *SetKey_arguments_gc_map = "10";
char *SetKey_locals_gc_map = "";

char *GetHas_Right_arguments_gc_map = "1";
char *GetHas_Right_locals_gc_map = "";

char *GetHas_Left_arguments_gc_map = "1";
char *GetHas_Left_locals_gc_map = "";

char *SetHas_Left_arguments_gc_map = "10";
char *SetHas_Left_locals_gc_map = "";

char *SetHas_Right_arguments_gc_map = "10";
char *SetHas_Right_locals_gc_map = "";

char *Compare_arguments_gc_map = "100";
char *Compare_locals_gc_map = "00";

char *Insert_arguments_gc_map = "10";
char *Insert_locals_gc_map = "10001";

char *Delete_arguments_gc_map = "10";
char *Delete_locals_gc_map = "1100000";

char *Remove_arguments_gc_map = "111";
char *Remove_locals_gc_map = "000";

char *RemoveRight_arguments_gc_map = "111";
char *RemoveRight_locals_gc_map = "0";

char *RemoveLeft_arguments_gc_map = "111";
char *RemoveLeft_locals_gc_map = "0";

char *Search_arguments_gc_map = "10";
char *Search_locals_gc_map = "0010";

char *Print_arguments_gc_map = "1";
char *Print_locals_gc_map = "10";

char *RecPrint_arguments_gc_map = "11";
char *RecPrint_locals_gc_map = "0";


//-----------------------methods declarations--------------------------
int BT_Start(void *prev, struct BT *this);
int Tree_Init(void *prev, struct Tree *this, int v_key);
int Tree_SetRight(void *prev, struct Tree *this, struct Tree *rn);
int Tree_SetLeft(void *prev, struct Tree *this, struct Tree *ln);
struct Tree *Tree_GetRight(void *prev, struct Tree *this);
struct Tree *Tree_GetLeft(void *prev, struct Tree *this);
int Tree_GetKey(void *prev, struct Tree *this);
int Tree_SetKey(void *prev, struct Tree *this, int v_key);
int Tree_GetHas_Right(void *prev, struct Tree *this);
int Tree_GetHas_Left(void *prev, struct Tree *this);
int Tree_SetHas_Left(void *prev, struct Tree *this, int val);
int Tree_SetHas_Right(void *prev, struct Tree *this, int val);
int Tree_Compare(void *prev, struct Tree *this, int num1, int num2);
int Tree_Insert(void *prev, struct Tree *this, int v_key);
int Tree_Delete(void *prev, struct Tree *this, int v_key);
int Tree_Remove(void *prev, struct Tree *this, struct Tree *p_node, struct Tree *c_node);
int Tree_RemoveRight(void *prev, struct Tree *this, struct Tree *p_node, struct Tree *c_node);
int Tree_RemoveLeft(void *prev, struct Tree *this, struct Tree *p_node, struct Tree *c_node);
int Tree_Search(void *prev, struct Tree *this, int v_key);
int Tree_Print(void *prev, struct Tree *this);
int Tree_RecPrint(void *prev, struct Tree *this, struct Tree *node);

//----------------------vtables--------------------------
struct BinaryTree_vtable BinaryTree_vtable_ = 
{
};

struct BT_vtable BT_vtable_ = 
{
  BT_Start
};

struct Tree_vtable Tree_vtable_ = 
{
  Tree_Init,
  Tree_SetRight,
  Tree_SetLeft,
  Tree_GetRight,
  Tree_GetLeft,
  Tree_GetKey,
  Tree_SetKey,
  Tree_GetHas_Right,
  Tree_GetHas_Left,
  Tree_SetHas_Left,
  Tree_SetHas_Right,
  Tree_Compare,
  Tree_Insert,
  Tree_Delete,
  Tree_Remove,
  Tree_RemoveRight,
  Tree_RemoveLeft,
  Tree_Search,
  Tree_Print,
  Tree_RecPrint
};


//------------------------methods' GC frame---------------------------
struct Start_gc_frame
{
  void *prev;
  char *Start_arg_gc_map;
  int *Start_arg_base_address;
  char *Start_local_gc_map;
  struct Tree * root;
  int  ntb;
  int  nti;
};

struct Init_gc_frame
{
  void *prev;
  char *Init_arg_gc_map;
  int *Init_arg_base_address;
  char *Init_local_gc_map;
};

struct SetRight_gc_frame
{
  void *prev;
  char *SetRight_arg_gc_map;
  int *SetRight_arg_base_address;
  char *SetRight_local_gc_map;
};

struct SetLeft_gc_frame
{
  void *prev;
  char *SetLeft_arg_gc_map;
  int *SetLeft_arg_base_address;
  char *SetLeft_local_gc_map;
};

struct GetRight_gc_frame
{
  void *prev;
  char *GetRight_arg_gc_map;
  int *GetRight_arg_base_address;
  char *GetRight_local_gc_map;
};

struct GetLeft_gc_frame
{
  void *prev;
  char *GetLeft_arg_gc_map;
  int *GetLeft_arg_base_address;
  char *GetLeft_local_gc_map;
};

struct GetKey_gc_frame
{
  void *prev;
  char *GetKey_arg_gc_map;
  int *GetKey_arg_base_address;
  char *GetKey_local_gc_map;
};

struct SetKey_gc_frame
{
  void *prev;
  char *SetKey_arg_gc_map;
  int *SetKey_arg_base_address;
  char *SetKey_local_gc_map;
};

struct GetHas_Right_gc_frame
{
  void *prev;
  char *GetHas_Right_arg_gc_map;
  int *GetHas_Right_arg_base_address;
  char *GetHas_Right_local_gc_map;
};

struct GetHas_Left_gc_frame
{
  void *prev;
  char *GetHas_Left_arg_gc_map;
  int *GetHas_Left_arg_base_address;
  char *GetHas_Left_local_gc_map;
};

struct SetHas_Left_gc_frame
{
  void *prev;
  char *SetHas_Left_arg_gc_map;
  int *SetHas_Left_arg_base_address;
  char *SetHas_Left_local_gc_map;
};

struct SetHas_Right_gc_frame
{
  void *prev;
  char *SetHas_Right_arg_gc_map;
  int *SetHas_Right_arg_base_address;
  char *SetHas_Right_local_gc_map;
};

struct Compare_gc_frame
{
  void *prev;
  char *Compare_arg_gc_map;
  int *Compare_arg_base_address;
  char *Compare_local_gc_map;
  int  ntb;
  int  nti;
};

struct Insert_gc_frame
{
  void *prev;
  char *Insert_arg_gc_map;
  int *Insert_arg_base_address;
  char *Insert_local_gc_map;
  struct Tree * new_node;
  int  ntb;
  int  cont;
  int  key_aux;
  struct Tree * current_node;
};

struct Delete_gc_frame
{
  void *prev;
  char *Delete_arg_gc_map;
  int *Delete_arg_base_address;
  char *Delete_local_gc_map;
  struct Tree * current_node;
  struct Tree * parent_node;
  int  cont;
  int  found;
  int  is_root;
  int  key_aux;
  int  ntb;
};

struct Remove_gc_frame
{
  void *prev;
  char *Remove_arg_gc_map;
  int *Remove_arg_base_address;
  char *Remove_local_gc_map;
  int  ntb;
  int  auxkey1;
  int  auxkey2;
};

struct RemoveRight_gc_frame
{
  void *prev;
  char *RemoveRight_arg_gc_map;
  int *RemoveRight_arg_base_address;
  char *RemoveRight_local_gc_map;
  int  ntb;
};

struct RemoveLeft_gc_frame
{
  void *prev;
  char *RemoveLeft_arg_gc_map;
  int *RemoveLeft_arg_base_address;
  char *RemoveLeft_local_gc_map;
  int  ntb;
};

struct Search_gc_frame
{
  void *prev;
  char *Search_arg_gc_map;
  int *Search_arg_base_address;
  char *Search_local_gc_map;
  int  cont;
  int  ifound;
  struct Tree * current_node;
  int  key_aux;
};

struct Print_gc_frame
{
  void *prev;
  char *Print_arg_gc_map;
  int *Print_arg_base_address;
  char *Print_local_gc_map;
  struct Tree * current_node;
  int  ntb;
};

struct RecPrint_gc_frame
{
  void *prev;
  char *RecPrint_arg_gc_map;
  int *RecPrint_arg_base_address;
  char *RecPrint_local_gc_map;
  int  ntb;
};


//--------------------------methods---------------------------
int BT_Start(void *prev, struct BT *this)
{
  struct Start_gc_frame Start_gc_frame_temp;

  Start_gc_frame_temp.prev = prev;
  Start_gc_frame_temp.Start_arg_gc_map = Start_arguments_gc_map;
  Start_gc_frame_temp.Start_arg_base_address = (int *)&this;
  Start_gc_frame_temp.Start_local_gc_map = Start_locals_gc_map;

  struct Tree * root;
  int  ntb;
  int  nti;

  root = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
  ntb = root->vptr->Init(root, 16);
  ntb = root->vptr->Print(root);
  System_out_println (100000000);
  ntb = root->vptr->Insert(root, 8);
  ntb = root->vptr->Print(root);
  ntb = root->vptr->Insert(root, 24);
  ntb = root->vptr->Insert(root, 4);
  ntb = root->vptr->Insert(root, 12);
  ntb = root->vptr->Insert(root, 20);
  ntb = root->vptr->Insert(root, 28);
  ntb = root->vptr->Insert(root, 14);
  ntb = root->vptr->Print(root);
  System_out_println (root->vptr->Search(root, 24));
  System_out_println (root->vptr->Search(root, 12));
  System_out_println (root->vptr->Search(root, 16));
  System_out_println (root->vptr->Search(root, 50));
  System_out_println (root->vptr->Search(root, 12));
  ntb = root->vptr->Delete(root, 12);
  ntb = root->vptr->Print(root);
  System_out_println (root->vptr->Search(root, 12));
  return 0;
}
int Tree_Init(void *prev, struct Tree *this, int v_key)
{
  struct Init_gc_frame Init_gc_frame_temp;

  Init_gc_frame_temp.prev = prev;
  Init_gc_frame_temp.Init_arg_gc_map = Init_arguments_gc_map;
  Init_gc_frame_temp.Init_arg_base_address = (int *)&this;
  Init_gc_frame_temp.Init_local_gc_map = Init_locals_gc_map;

  this->key = v_key;
  this->has_left = 0;
  this->has_right = 0;
  return 1;
}
int Tree_SetRight(void *prev, struct Tree *this, struct Tree *rn)
{
  struct SetRight_gc_frame SetRight_gc_frame_temp;

  SetRight_gc_frame_temp.prev = prev;
  SetRight_gc_frame_temp.SetRight_arg_gc_map = SetRight_arguments_gc_map;
  SetRight_gc_frame_temp.SetRight_arg_base_address = (int *)&this;
  SetRight_gc_frame_temp.SetRight_local_gc_map = SetRight_locals_gc_map;

  this->right = rn;
  return 1;
}
int Tree_SetLeft(void *prev, struct Tree *this, struct Tree *ln)
{
  struct SetLeft_gc_frame SetLeft_gc_frame_temp;

  SetLeft_gc_frame_temp.prev = prev;
  SetLeft_gc_frame_temp.SetLeft_arg_gc_map = SetLeft_arguments_gc_map;
  SetLeft_gc_frame_temp.SetLeft_arg_base_address = (int *)&this;
  SetLeft_gc_frame_temp.SetLeft_local_gc_map = SetLeft_locals_gc_map;

  this->left = ln;
  return 1;
}
struct Tree *Tree_GetRight(void *prev, struct Tree *this)
{
  struct GetRight_gc_frame GetRight_gc_frame_temp;

  GetRight_gc_frame_temp.prev = prev;
  GetRight_gc_frame_temp.GetRight_arg_gc_map = GetRight_arguments_gc_map;
  GetRight_gc_frame_temp.GetRight_arg_base_address = (int *)&this;
  GetRight_gc_frame_temp.GetRight_local_gc_map = GetRight_locals_gc_map;

  return this->right;
}
struct Tree *Tree_GetLeft(void *prev, struct Tree *this)
{
  struct GetLeft_gc_frame GetLeft_gc_frame_temp;

  GetLeft_gc_frame_temp.prev = prev;
  GetLeft_gc_frame_temp.GetLeft_arg_gc_map = GetLeft_arguments_gc_map;
  GetLeft_gc_frame_temp.GetLeft_arg_base_address = (int *)&this;
  GetLeft_gc_frame_temp.GetLeft_local_gc_map = GetLeft_locals_gc_map;

  return this->left;
}
int Tree_GetKey(void *prev, struct Tree *this)
{
  struct GetKey_gc_frame GetKey_gc_frame_temp;

  GetKey_gc_frame_temp.prev = prev;
  GetKey_gc_frame_temp.GetKey_arg_gc_map = GetKey_arguments_gc_map;
  GetKey_gc_frame_temp.GetKey_arg_base_address = (int *)&this;
  GetKey_gc_frame_temp.GetKey_local_gc_map = GetKey_locals_gc_map;

  return this->key;
}
int Tree_SetKey(void *prev, struct Tree *this, int v_key)
{
  struct SetKey_gc_frame SetKey_gc_frame_temp;

  SetKey_gc_frame_temp.prev = prev;
  SetKey_gc_frame_temp.SetKey_arg_gc_map = SetKey_arguments_gc_map;
  SetKey_gc_frame_temp.SetKey_arg_base_address = (int *)&this;
  SetKey_gc_frame_temp.SetKey_local_gc_map = SetKey_locals_gc_map;

  this->key = v_key;
  return 1;
}
int Tree_GetHas_Right(void *prev, struct Tree *this)
{
  struct GetHas_Right_gc_frame GetHas_Right_gc_frame_temp;

  GetHas_Right_gc_frame_temp.prev = prev;
  GetHas_Right_gc_frame_temp.GetHas_Right_arg_gc_map = GetHas_Right_arguments_gc_map;
  GetHas_Right_gc_frame_temp.GetHas_Right_arg_base_address = (int *)&this;
  GetHas_Right_gc_frame_temp.GetHas_Right_local_gc_map = GetHas_Right_locals_gc_map;

  return this->has_right;
}
int Tree_GetHas_Left(void *prev, struct Tree *this)
{
  struct GetHas_Left_gc_frame GetHas_Left_gc_frame_temp;

  GetHas_Left_gc_frame_temp.prev = prev;
  GetHas_Left_gc_frame_temp.GetHas_Left_arg_gc_map = GetHas_Left_arguments_gc_map;
  GetHas_Left_gc_frame_temp.GetHas_Left_arg_base_address = (int *)&this;
  GetHas_Left_gc_frame_temp.GetHas_Left_local_gc_map = GetHas_Left_locals_gc_map;

  return this->has_left;
}
int Tree_SetHas_Left(void *prev, struct Tree *this, int val)
{
  struct SetHas_Left_gc_frame SetHas_Left_gc_frame_temp;

  SetHas_Left_gc_frame_temp.prev = prev;
  SetHas_Left_gc_frame_temp.SetHas_Left_arg_gc_map = SetHas_Left_arguments_gc_map;
  SetHas_Left_gc_frame_temp.SetHas_Left_arg_base_address = (int *)&this;
  SetHas_Left_gc_frame_temp.SetHas_Left_local_gc_map = SetHas_Left_locals_gc_map;

  this->has_left = val;
  return 1;
}
int Tree_SetHas_Right(void *prev, struct Tree *this, int val)
{
  struct SetHas_Right_gc_frame SetHas_Right_gc_frame_temp;

  SetHas_Right_gc_frame_temp.prev = prev;
  SetHas_Right_gc_frame_temp.SetHas_Right_arg_gc_map = SetHas_Right_arguments_gc_map;
  SetHas_Right_gc_frame_temp.SetHas_Right_arg_base_address = (int *)&this;
  SetHas_Right_gc_frame_temp.SetHas_Right_local_gc_map = SetHas_Right_locals_gc_map;

  this->has_right = val;
  return 1;
}
int Tree_Compare(void *prev, struct Tree *this, int num1, int num2)
{
  struct Compare_gc_frame Compare_gc_frame_temp;

  Compare_gc_frame_temp.prev = prev;
  Compare_gc_frame_temp.Compare_arg_gc_map = Compare_arguments_gc_map;
  Compare_gc_frame_temp.Compare_arg_base_address = (int *)&this;
  Compare_gc_frame_temp.Compare_local_gc_map = Compare_locals_gc_map;

  int  ntb;
  int  nti;

  ntb = 0;
  nti = num2 + 1;
  if (num1 < num2)
    ntb = 0;
  else if (!(num1 < nti))
    ntb = 0;
  else
    ntb = 1;
  return ntb;
}
int Tree_Insert(void *prev, struct Tree *this, int v_key)
{
  struct Insert_gc_frame Insert_gc_frame_temp;

  Insert_gc_frame_temp.prev = prev;
  Insert_gc_frame_temp.Insert_arg_gc_map = Insert_arguments_gc_map;
  Insert_gc_frame_temp.Insert_arg_base_address = (int *)&this;
  Insert_gc_frame_temp.Insert_local_gc_map = Insert_locals_gc_map;

  struct Tree * new_node;
  int  ntb;
  int  cont;
  int  key_aux;
  struct Tree * current_node;

  new_node = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
  ntb = new_node->vptr->Init(new_node, v_key);
  current_node = this;
  cont = 1;
  while (cont)
  {
    key_aux = current_node->vptr->GetKey(current_node);
    if (v_key < key_aux)
    {
      if (current_node->vptr->GetHas_Left(current_node))
        current_node = current_node->vptr->GetLeft(current_node);
      else
      {
        cont = 0;
        ntb = current_node->vptr->SetHas_Left(current_node, 1);
        ntb = current_node->vptr->SetLeft(current_node, new_node);
      }
    }
    else
    {
      if (current_node->vptr->GetHas_Right(current_node))
        current_node = current_node->vptr->GetRight(current_node);
      else
      {
        cont = 0;
        ntb = current_node->vptr->SetHas_Right(current_node, 1);
        ntb = current_node->vptr->SetRight(current_node, new_node);
      }
    }
  }
  return 1;
}
int Tree_Delete(void *prev, struct Tree *this, int v_key)
{
  struct Delete_gc_frame Delete_gc_frame_temp;

  Delete_gc_frame_temp.prev = prev;
  Delete_gc_frame_temp.Delete_arg_gc_map = Delete_arguments_gc_map;
  Delete_gc_frame_temp.Delete_arg_base_address = (int *)&this;
  Delete_gc_frame_temp.Delete_local_gc_map = Delete_locals_gc_map;

  struct Tree * current_node;
  struct Tree * parent_node;
  int  cont;
  int  found;
  int  is_root;
  int  key_aux;
  int  ntb;

  current_node = this;
  parent_node = this;
  cont = 1;
  found = 0;
  is_root = 1;
  while (cont)
  {
    key_aux = current_node->vptr->GetKey(current_node);
    if (v_key < key_aux)
      if (current_node->vptr->GetHas_Left(current_node))
      {
        parent_node = current_node;
        current_node = current_node->vptr->GetLeft(current_node);
      }
      else
        cont = 0;
    else if (key_aux < v_key)
      if (current_node->vptr->GetHas_Right(current_node))
      {
        parent_node = current_node;
        current_node = current_node->vptr->GetRight(current_node);
      }
      else
        cont = 0;
    else
    {
      if (is_root)
        if (!(current_node->vptr->GetHas_Right(current_node)) && !(current_node->vptr->GetHas_Left(current_node)))
          ntb = 1;
        else
          ntb = this->vptr->Remove(this, parent_node, current_node);
      else
        ntb = this->vptr->Remove(this, parent_node, current_node);
      found = 1;
      cont = 0;
    }
    is_root = 0;
  }
  return found;
}
int Tree_Remove(void *prev, struct Tree *this, struct Tree *p_node, struct Tree *c_node)
{
  struct Remove_gc_frame Remove_gc_frame_temp;

  Remove_gc_frame_temp.prev = prev;
  Remove_gc_frame_temp.Remove_arg_gc_map = Remove_arguments_gc_map;
  Remove_gc_frame_temp.Remove_arg_base_address = (int *)&this;
  Remove_gc_frame_temp.Remove_local_gc_map = Remove_locals_gc_map;

  int  ntb;
  int  auxkey1;
  int  auxkey2;

  if (c_node->vptr->GetHas_Left(c_node))
    ntb = this->vptr->RemoveLeft(this, p_node, c_node);
  else if (c_node->vptr->GetHas_Right(c_node))
    ntb = this->vptr->RemoveRight(this, p_node, c_node);
  else
  {
    auxkey1 = c_node->vptr->GetKey(c_node);
    auxkey2 = p_node->vptr->GetLeft(p_node)->vptr->GetKey(p_node->vptr->GetLeft(p_node));
    if (this->vptr->Compare(this, auxkey1, auxkey2))
    {
      ntb = p_node->vptr->SetLeft(p_node, this->my_null);
      ntb = p_node->vptr->SetHas_Left(p_node, 0);
    }
    else
    {
      ntb = p_node->vptr->SetRight(p_node, this->my_null);
      ntb = p_node->vptr->SetHas_Right(p_node, 0);
    }
  }
  return 1;
}
int Tree_RemoveRight(void *prev, struct Tree *this, struct Tree *p_node, struct Tree *c_node)
{
  struct RemoveRight_gc_frame RemoveRight_gc_frame_temp;

  RemoveRight_gc_frame_temp.prev = prev;
  RemoveRight_gc_frame_temp.RemoveRight_arg_gc_map = RemoveRight_arguments_gc_map;
  RemoveRight_gc_frame_temp.RemoveRight_arg_base_address = (int *)&this;
  RemoveRight_gc_frame_temp.RemoveRight_local_gc_map = RemoveRight_locals_gc_map;

  int  ntb;

  while (c_node->vptr->GetHas_Right(c_node))
  {
    ntb = c_node->vptr->SetKey(c_node, c_node->vptr->GetRight(c_node)->vptr->GetKey(c_node->vptr->GetRight(c_node)));
    p_node = c_node;
    c_node = c_node->vptr->GetRight(c_node);
  }
  ntb = p_node->vptr->SetRight(p_node, this->my_null);
  ntb = p_node->vptr->SetHas_Right(p_node, 0);
  return 1;
}
int Tree_RemoveLeft(void *prev, struct Tree *this, struct Tree *p_node, struct Tree *c_node)
{
  struct RemoveLeft_gc_frame RemoveLeft_gc_frame_temp;

  RemoveLeft_gc_frame_temp.prev = prev;
  RemoveLeft_gc_frame_temp.RemoveLeft_arg_gc_map = RemoveLeft_arguments_gc_map;
  RemoveLeft_gc_frame_temp.RemoveLeft_arg_base_address = (int *)&this;
  RemoveLeft_gc_frame_temp.RemoveLeft_local_gc_map = RemoveLeft_locals_gc_map;

  int  ntb;

  while (c_node->vptr->GetHas_Left(c_node))
  {
    ntb = c_node->vptr->SetKey(c_node, c_node->vptr->GetLeft(c_node)->vptr->GetKey(c_node->vptr->GetLeft(c_node)));
    p_node = c_node;
    c_node = c_node->vptr->GetLeft(c_node);
  }
  ntb = p_node->vptr->SetLeft(p_node, this->my_null);
  ntb = p_node->vptr->SetHas_Left(p_node, 0);
  return 1;
}
int Tree_Search(void *prev, struct Tree *this, int v_key)
{
  struct Search_gc_frame Search_gc_frame_temp;

  Search_gc_frame_temp.prev = prev;
  Search_gc_frame_temp.Search_arg_gc_map = Search_arguments_gc_map;
  Search_gc_frame_temp.Search_arg_base_address = (int *)&this;
  Search_gc_frame_temp.Search_local_gc_map = Search_locals_gc_map;

  int  cont;
  int  ifound;
  struct Tree * current_node;
  int  key_aux;

  current_node = this;
  cont = 1;
  ifound = 0;
  while (cont)
  {
    key_aux = current_node->vptr->GetKey(current_node);
    if (v_key < key_aux)
      if (current_node->vptr->GetHas_Left(current_node))
        current_node = current_node->vptr->GetLeft(current_node);
      else
        cont = 0;
    else if (key_aux < v_key)
      if (current_node->vptr->GetHas_Right(current_node))
        current_node = current_node->vptr->GetRight(current_node);
      else
        cont = 0;
    else
    {
      ifound = 1;
      cont = 0;
    }
  }
  return ifound;
}
int Tree_Print(void *prev, struct Tree *this)
{
  struct Print_gc_frame Print_gc_frame_temp;

  Print_gc_frame_temp.prev = prev;
  Print_gc_frame_temp.Print_arg_gc_map = Print_arguments_gc_map;
  Print_gc_frame_temp.Print_arg_base_address = (int *)&this;
  Print_gc_frame_temp.Print_local_gc_map = Print_locals_gc_map;

  struct Tree * current_node;
  int  ntb;

  current_node = this;
  ntb = this->vptr->RecPrint(this, current_node);
  return 1;
}
int Tree_RecPrint(void *prev, struct Tree *this, struct Tree *node)
{
  struct RecPrint_gc_frame RecPrint_gc_frame_temp;

  RecPrint_gc_frame_temp.prev = prev;
  RecPrint_gc_frame_temp.RecPrint_arg_gc_map = RecPrint_arguments_gc_map;
  RecPrint_gc_frame_temp.RecPrint_arg_base_address = (int *)&this;
  RecPrint_gc_frame_temp.RecPrint_local_gc_map = RecPrint_locals_gc_map;

  int  ntb;

  if (node->vptr->GetHas_Left(node))
  {
    ntb = this->vptr->RecPrint(this, node->vptr->GetLeft(node));
  }
  else
    ntb = 1;
  System_out_println (node->vptr->GetKey(node));
  if (node->vptr->GetHas_Right(node))
  {
    ntb = this->vptr->RecPrint(this, node->vptr->GetRight(node));
  }
  else
    ntb = 1;
  return 1;
}

//-----------------------main method-----------------------
int Tiger_main ()
{
  struct BT *temp_1;
  System_out_println ((temp_1=((struct BT*)(Tiger_new (&BT_vtable_, sizeof(struct BT)))), temp_1->vptr->Start(temp_1)));
}




