// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct intArray
{
  int length;
  int *array;
};

struct BubbleSort
{
  struct BubbleSort_vtable *vptr;
};
struct BBS
{
  struct BBS_vtable *vptr;
  struct intArray * number;
  int  size;
};
// vtables structures
struct BubbleSort_vtable
{
};

struct BBS_vtable
{
  int (*Start)(struct BBS *, int);
  int (*Sort)(struct BBS *);
  int (*Print)(struct BBS *);
  int (*Init)(struct BBS *, int);
};


// methods declarations
int BBS_Start(struct BBS *this, int sz);
int BBS_Sort(struct BBS *this);
int BBS_Print(struct BBS *this);
int BBS_Init(struct BBS *this, int sz);

// vtables
struct BubbleSort_vtable BubbleSort_vtable_ = 
{
};

struct BBS_vtable BBS_vtable_ = 
{
  BBS_Start,
  BBS_Sort,
  BBS_Print,
  BBS_Init
};


// methods
int BBS_Start(struct BBS *this, int sz)
{
  int  aux01;

  aux01 = this->vptr->Init(this, sz);
  aux01 = this->vptr->Print(this);
  System_out_println (99999);
  aux01 = this->vptr->Sort(this);
  aux01 = this->vptr->Print(this);
  return 0;
}
int BBS_Sort(struct BBS *this)
{
  int  nt;
  int  i;
  int  aux02;
  int  aux04;
  int  aux05;
  int  aux06;
  int  aux07;
  int  j;
  int  t;

  i = this->size - 1;
  aux02 = 0 - 1;
  while (aux02 < i)
  {
    j = 1;
    while (j < i + 1)
    {
      aux07 = j - 1;
      aux04 = this->number->array[aux07];
      aux05 = this->number->array[j];
      if (aux05 < aux04)
      {
        aux06 = j - 1;
        t = this->number->array[aux06];
        this->number->array[aux06] = this->number->array[j];
        this->number->array[j] = t;
      }
      else
        nt = 0;
      j = j + 1;
    }
    i = i - 1;
  }
  return 0;
}
int BBS_Print(struct BBS *this)
{
  int  j;

  j = 0;
  while (j < this->size)
  {
    System_out_println (this->number->array[j]);
    j = j + 1;
  }
  return 0;
}
int BBS_Init(struct BBS *this, int sz)
{
  this->size = sz;
  this->number = (struct intArray *)malloc(sizeof(struct intArray));
  this->number->length = sz;
  this->number->array = (int *)malloc((sz)*sizeof(int));
  this->number->array[0] = 20;
  this->number->array[1] = 7;
  this->number->array[2] = 12;
  this->number->array[3] = 18;
  this->number->array[4] = 2;
  this->number->array[5] = 11;
  this->number->array[6] = 6;
  this->number->array[7] = 9;
  this->number->array[8] = 19;
  this->number->array[9] = 5;
  return 0;
}

// main method
int Tiger_main ()
{
  struct BBS *temp_1;
  System_out_println ((temp_1=((struct BBS*)(Tiger_new (&BBS_vtable_, sizeof(struct BBS)))), temp_1->vptr->Start(temp_1, 10)));
}




