// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct intArray
{
  int length;
  int *array;
};

struct LinearSearch
{
  struct LinearSearch_vtable *vptr;
};
struct LS
{
  struct LS_vtable *vptr;
  struct intArray * number;
  int  size;
};
// vtables structures
struct LinearSearch_vtable
{
};

struct LS_vtable
{
  int (*Start)(struct LS *, int);
  int (*Print)(struct LS *);
  int (*Search)(struct LS *, int);
  int (*Init)(struct LS *, int);
};


// methods declarations
int LS_Start(struct LS *this, int sz);
int LS_Print(struct LS *this);
int LS_Search(struct LS *this, int num);
int LS_Init(struct LS *this, int sz);

// vtables
struct LinearSearch_vtable LinearSearch_vtable_ = 
{
};

struct LS_vtable LS_vtable_ = 
{
  LS_Start,
  LS_Print,
  LS_Search,
  LS_Init
};


// methods
int LS_Start(struct LS *this, int sz)
{
  int  aux01;
  int  aux02;

  aux01 = this->vptr->Init(this, sz);
  aux02 = this->vptr->Print(this);
  System_out_println (9999);
  System_out_println (this->vptr->Search(this, 8));
  System_out_println (this->vptr->Search(this, 12));
  System_out_println (this->vptr->Search(this, 17));
  System_out_println (this->vptr->Search(this, 50));
  return 55;
}
int LS_Print(struct LS *this)
{
  int  j;

  j = 1;
  while (j < this->size)
  {
    System_out_println (this->number->array[j]);
    j = j + 1;
  }
  return 0;
}
int LS_Search(struct LS *this, int num)
{
  int  j;
  int  ls01;
  int  ifound;
  int  aux01;
  int  aux02;
  int  nt;

  j = 1;
  ls01 = 0;
  ifound = 0;
  while (j < this->size)
  {
    aux01 = this->number->array[j];
    aux02 = num + 1;
    if (aux01 < num)
      nt = 0;
    else if (!(aux01 < aux02))
      nt = 0;
    else
    {
      ls01 = 1;
      ifound = 1;
      j = this->size;
    }
    j = j + 1;
  }
  return ifound;
}
int LS_Init(struct LS *this, int sz)
{
  int  j;
  int  k;
  int  aux01;
  int  aux02;

  this->size = sz;
  this->number = (struct intArray *)malloc(sizeof(struct intArray));
  this->number->length = sz;
  this->number->array = (int *)malloc((sz)*sizeof(int));
  j = 1;
  k = this->size + 1;
  while (j < this->size)
  {
    aux01 = 2 * j;
    aux02 = k - 3;
    this->number->array[j] = aux01 + aux02;
    j = j + 1;
    k = k - 1;
  }
  return 0;
}

// main method
int Tiger_main ()
{
  struct LS *temp_1;
  System_out_println ((temp_1=((struct LS*)(Tiger_new (&LS_vtable_, sizeof(struct LS)))), temp_1->vptr->Start(temp_1, 10)));
}




