// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct intArray
{
  int length;
  int *array;
};

struct LinkedList
{
  struct LinkedList_vtable *vptr;
};
struct Element
{
  struct Element_vtable *vptr;
  int  Age;
  int  Salary;
  int  Married;
};
struct List
{
  struct List_vtable *vptr;
  struct Element * elem;
  struct List * next;
  int  end;
};
struct LL
{
  struct LL_vtable *vptr;
};
// vtables structures
struct LinkedList_vtable
{
};

struct Element_vtable
{
  int (*Init)(struct Element *, int, int, int);
  int (*GetAge)(struct Element *);
  int (*GetSalary)(struct Element *);
  int (*GetMarried)(struct Element *);
  int (*Equal)(struct Element *, struct Element *);
  int (*Compare)(struct Element *, int, int);
};

struct List_vtable
{
  int (*Init)(struct List *);
  int (*InitNew)(struct List *, struct Element *, struct List *, int);
  struct List *(*Insert)(struct List *, struct Element *);
  int (*SetNext)(struct List *, struct List *);
  struct List *(*Delete)(struct List *, struct Element *);
  int (*Search)(struct List *, struct Element *);
  int (*GetEnd)(struct List *);
  struct Element *(*GetElem)(struct List *);
  struct List *(*GetNext)(struct List *);
  int (*Print)(struct List *);
};

struct LL_vtable
{
  int (*Start)(struct LL *);
};


// methods declarations
int Element_Init(struct Element *this, int v_Age, int v_Salary, int v_Married);
int Element_GetAge(struct Element *this);
int Element_GetSalary(struct Element *this);
int Element_GetMarried(struct Element *this);
int Element_Equal(struct Element *this, struct Element *other);
int Element_Compare(struct Element *this, int num1, int num2);
int List_Init(struct List *this);
int List_InitNew(struct List *this, struct Element *v_elem, struct List *v_next, int v_end);
struct List *List_Insert(struct List *this, struct Element *new_elem);
int List_SetNext(struct List *this, struct List *v_next);
struct List *List_Delete(struct List *this, struct Element *e);
int List_Search(struct List *this, struct Element *e);
int List_GetEnd(struct List *this);
struct Element *List_GetElem(struct List *this);
struct List *List_GetNext(struct List *this);
int List_Print(struct List *this);
int LL_Start(struct LL *this);

// vtables
struct LinkedList_vtable LinkedList_vtable_ = 
{
};

struct Element_vtable Element_vtable_ = 
{
  Element_Init,
  Element_GetAge,
  Element_GetSalary,
  Element_GetMarried,
  Element_Equal,
  Element_Compare
};

struct List_vtable List_vtable_ = 
{
  List_Init,
  List_InitNew,
  List_Insert,
  List_SetNext,
  List_Delete,
  List_Search,
  List_GetEnd,
  List_GetElem,
  List_GetNext,
  List_Print
};

struct LL_vtable LL_vtable_ = 
{
  LL_Start
};


// methods
int Element_Init(struct Element *this, int v_Age, int v_Salary, int v_Married)
{
  this->Age = v_Age;
  this->Salary = v_Salary;
  this->Married = v_Married;
  return 1;
}
int Element_GetAge(struct Element *this)
{
  return this->Age;
}
int Element_GetSalary(struct Element *this)
{
  return this->Salary;
}
int Element_GetMarried(struct Element *this)
{
  return this->Married;
}
int Element_Equal(struct Element *this, struct Element *other)
{
  int  ret_val;
  int  aux01;
  int  aux02;
  int  nt;

  ret_val = 1;
  aux01 = other->vptr->GetAge(other);
  if (!(this->vptr->Compare(this, aux01, this->Age)))
    ret_val = 0;
  else
  {
    aux02 = other->vptr->GetSalary(other);
    if (!(this->vptr->Compare(this, aux02, this->Salary)))
      ret_val = 0;
    else if (this->Married)
      if (!(other->vptr->GetMarried(other)))
        ret_val = 0;
      else
        nt = 0;
    else if (other->vptr->GetMarried(other))
      ret_val = 0;
    else
      nt = 0;
  }
  return ret_val;
}
int Element_Compare(struct Element *this, int num1, int num2)
{
  int  retval;
  int  aux02;

  retval = 0;
  aux02 = num2 + 1;
  if (num1 < num2)
    retval = 0;
  else if (!(num1 < aux02))
    retval = 0;
  else
    retval = 1;
  return retval;
}
int List_Init(struct List *this)
{
  this->end = 1;
  return 1;
}
int List_InitNew(struct List *this, struct Element *v_elem, struct List *v_next, int v_end)
{
  this->end = v_end;
  this->elem = v_elem;
  this->next = v_next;
  return 1;
}
struct List *List_Insert(struct List *this, struct Element *new_elem)
{
  int  ret_val;
  struct List * aux03;
  struct List * aux02;

  aux03 = this;
  aux02 = ((struct List*)(Tiger_new (&List_vtable_, sizeof(struct List))));
  ret_val = aux02->vptr->InitNew(aux02, new_elem, aux03, 0);
  return aux02;
}
int List_SetNext(struct List *this, struct List *v_next)
{
  this->next = v_next;
  return 1;
}
struct List *List_Delete(struct List *this, struct Element *e)
{
  struct List * my_head;
  int  ret_val;
  int  aux05;
  struct List * aux01;
  struct List * prev;
  int  var_end;
  struct Element * var_elem;
  int  aux04;
  int  nt;

  my_head = this;
  ret_val = 0;
  aux04 = 0 - 1;
  aux01 = this;
  prev = this;
  var_end = this->end;
  var_elem = this->elem;
  while (!(var_end) && !(ret_val))
  {
    if (e->vptr->Equal(e, var_elem))
    {
      ret_val = 1;
      if (aux04 < 0)
      {
        my_head = aux01->vptr->GetNext(aux01);
      }
      else
      {
        System_out_println (0 - 555);
        aux05 = prev->vptr->SetNext(prev, aux01->vptr->GetNext(aux01));
        System_out_println (0 - 555);
      }
    }
    else
      nt = 0;
    if (!(ret_val))
    {
      prev = aux01;
      aux01 = aux01->vptr->GetNext(aux01);
      var_end = aux01->vptr->GetEnd(aux01);
      var_elem = aux01->vptr->GetElem(aux01);
      aux04 = 1;
    }
    else
      nt = 0;
  }
  return my_head;
}
int List_Search(struct List *this, struct Element *e)
{
  int  int_ret_val;
  struct List * aux01;
  struct Element * var_elem;
  int  var_end;
  int  nt;

  int_ret_val = 0;
  aux01 = this;
  var_end = this->end;
  var_elem = this->elem;
  while (!(var_end))
  {
    if (e->vptr->Equal(e, var_elem))
    {
      int_ret_val = 1;
    }
    else
      nt = 0;
    aux01 = aux01->vptr->GetNext(aux01);
    var_end = aux01->vptr->GetEnd(aux01);
    var_elem = aux01->vptr->GetElem(aux01);
  }
  return int_ret_val;
}
int List_GetEnd(struct List *this)
{
  return this->end;
}
struct Element *List_GetElem(struct List *this)
{
  return this->elem;
}
struct List *List_GetNext(struct List *this)
{
  return this->next;
}
int List_Print(struct List *this)
{
  struct List * aux01;
  int  var_end;
  struct Element * var_elem;

  aux01 = this;
  var_end = this->end;
  var_elem = this->elem;
  while (!(var_end))
  {
    System_out_println (var_elem->vptr->GetAge(var_elem));
    aux01 = aux01->vptr->GetNext(aux01);
    var_end = aux01->vptr->GetEnd(aux01);
    var_elem = aux01->vptr->GetElem(aux01);
  }
  return 1;
}
int LL_Start(struct LL *this)
{
  struct List * head;
  struct List * last_elem;
  int  aux01;
  struct Element * el01;
  struct Element * el02;
  struct Element * el03;

  last_elem = ((struct List*)(Tiger_new (&List_vtable_, sizeof(struct List))));
  aux01 = last_elem->vptr->Init(last_elem);
  head = last_elem;
  aux01 = head->vptr->Init(head);
  aux01 = head->vptr->Print(head);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = el01->vptr->Init(el01, 25, 37000, 0);
  head = head->vptr->Insert(head, el01);
  aux01 = head->vptr->Print(head);
  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = el01->vptr->Init(el01, 39, 42000, 1);
  el02 = el01;
  head = head->vptr->Insert(head, el01);
  aux01 = head->vptr->Print(head);
  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = el01->vptr->Init(el01, 22, 34000, 0);
  head = head->vptr->Insert(head, el01);
  aux01 = head->vptr->Print(head);
  el03 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = el03->vptr->Init(el03, 27, 34000, 0);
  System_out_println (head->vptr->Search(head, el02));
  System_out_println (head->vptr->Search(head, el03));
  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = el01->vptr->Init(el01, 28, 35000, 0);
  head = head->vptr->Insert(head, el01);
  aux01 = head->vptr->Print(head);
  System_out_println (2220000);
  head = head->vptr->Delete(head, el02);
  aux01 = head->vptr->Print(head);
  System_out_println (33300000);
  head = head->vptr->Delete(head, el01);
  aux01 = head->vptr->Print(head);
  System_out_println (44440000);
  return 0;
}

// main method
int Tiger_main ()
{
  struct LL *temp_1;
  System_out_println ((temp_1=((struct LL*)(Tiger_new (&LL_vtable_, sizeof(struct LL)))), temp_1->vptr->Start(temp_1)));
}




