// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct intArray
{
  int length;
  int *array;
};

struct QuickSort
{
  struct QuickSort_vtable *vptr;
};
struct QS
{
  struct QS_vtable *vptr;
  struct intArray * number;
  int  size;
};
// vtables structures
struct QuickSort_vtable
{
};

struct QS_vtable
{
  int (*Start)(struct QS *, int);
  int (*Sort)(struct QS *, int, int);
  int (*Print)(struct QS *);
  int (*Init)(struct QS *, int);
};


// methods declarations
int QS_Start(struct QS *this, int sz);
int QS_Sort(struct QS *this, int left, int right);
int QS_Print(struct QS *this);
int QS_Init(struct QS *this, int sz);

// vtables
struct QuickSort_vtable QuickSort_vtable_ = 
{
};

struct QS_vtable QS_vtable_ = 
{
  QS_Start,
  QS_Sort,
  QS_Print,
  QS_Init
};


// methods
int QS_Start(struct QS *this, int sz)
{
  int  aux01;

  aux01 = this->vptr->Init(this, sz);
  aux01 = this->vptr->Print(this);
  System_out_println (9999);
  aux01 = this->size - 1;
  aux01 = this->vptr->Sort(this, 0, aux01);
  aux01 = this->vptr->Print(this);
  return 0;
}
int QS_Sort(struct QS *this, int left, int right)
{
  int  v;
  int  i;
  int  j;
  int  nt;
  int  t;
  int  cont01;
  int  cont02;
  int  aux03;

  t = 0;
  if (left < right)
  {
    v = this->number->array[right];
    i = left - 1;
    j = right;
    cont01 = 1;
    while (cont01)
    {
      cont02 = 1;
      while (cont02)
      {
        i = i + 1;
        aux03 = this->number->array[i];
        if (!(aux03 < v))
          cont02 = 0;
        else
          cont02 = 1;
      }
      cont02 = 1;
      while (cont02)
      {
        j = j - 1;
        aux03 = this->number->array[j];
        if (!(v < aux03))
          cont02 = 0;
        else
          cont02 = 1;
      }
      t = this->number->array[i];
      this->number->array[i] = this->number->array[j];
      this->number->array[j] = t;
      if (j < i + 1)
        cont01 = 0;
      else
        cont01 = 1;
    }
    this->number->array[j] = this->number->array[i];
    this->number->array[i] = this->number->array[right];
    this->number->array[right] = t;
    nt = this->vptr->Sort(this, left, i - 1);
    nt = this->vptr->Sort(this, i + 1, right);
  }
  else
    nt = 0;
  return 0;
}
int QS_Print(struct QS *this)
{
  int  j;

  j = 0;
  while (j < this->size)
  {
    System_out_println (this->number->array[j]);
    j = j + 1;
  }
  return 0;
}
int QS_Init(struct QS *this, int sz)
{
  this->size = sz;
  this->number = (struct intArray *)malloc(sizeof(struct intArray));
  this->number->length = sz;
  this->number->array = (int *)malloc((sz)*sizeof(int));
  this->number->array[0] = 20;
  this->number->array[1] = 7;
  this->number->array[2] = 12;
  this->number->array[3] = 18;
  this->number->array[4] = 2;
  this->number->array[5] = 11;
  this->number->array[6] = 6;
  this->number->array[7] = 9;
  this->number->array[8] = 19;
  this->number->array[9] = 5;
  return 0;
}

// main method
int Tiger_main ()
{
  struct QS *temp_1;
  System_out_println ((temp_1=((struct QS*)(Tiger_new (&QS_vtable_, sizeof(struct QS)))), temp_1->vptr->Start(temp_1, 10)));
}




